### ISSUE TITLE
Novaflare Pause Music needs to be adjusted

### ISSUE THREAD

**Issue by DaffyToons** [28AloneDark53/Psych-Extended#1]
### Describe your bug here.

Well, this is only present in the Novaflare Pause, Normally when you pause the game with the normal one, it starts without music , but then it slowly fades in at a moderate volume, something that doesn't happen in the Novaflare Pause. You pause the game and the music is instant, and full volume, which is really noticeable in songs that have a Low Volume like "Bite (Fernan Mix)"

https://github.com/user-attachments/assets/bdff29a9-4166-40b7-b451-c25ed564cf03

I've been syncing my fork of this repository with each update, so i hope that the next one fixes the volume of the Novaflare Pause

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Well, a couple of basic stuff, basically my usual changes that i do to the engines that i use

**Comment by 28AloneDark53** [comment]
> ### Hatanızı buraya açıklayın.
> Bu sadece Novaflare Duraklatma'da mevcut. Normalde oyunu normal olanla duraklattığınızda, müziksiz başlıyor ancak sonra yavaş yavaş orta seviyede bir seste azalıyor, bu Novaflare Duraklatma'da olmuyor. Oyunu duraklatıyorsunuz ve müzik anında ve tam seste oluyor, bu da "Bite (Fernan Mix)" gibi Düşük Ses Seviyesine sahip şarkılarda gerçekten fark ediliyor.
> 
>  Ekran_Kaydı_20241201_175438.mp4 
> Bu deponun çatalını her güncellemeyle senkronize ediyorum, bu yüzden bir sonraki güncellemenin Novaflare Duraklamasının hacmini düzeltmesini umuyorum
> 
> ### Komut İstemi/Terminal günlükleri (varsa)
> _Cevap yok_
> 
> ### Bir yapıyı kaynak koddan mı yoksa Lua ile mi modluyorsunuz?
> Lua
> 
> ### İnşa hedefiniz nedir?
> Android
> 
> ### Bu yapıda herhangi bir şeyi düzenlediniz mi? Eğer öyleyse, değişikliklerinizden bahsedin veya özetleyin.
> Pekala, birkaç temel şey, temel olarak kullandığım motorlarda yaptığım olağan değişiklikler

Idk how NovaFlare Pause Menu works, you need to try NovaFlare Engine, if NovaFlare Engine has the same problem you need to tell beihu

**Comment by ArkoseLabsOfficial** [comment]
Fixed
